
package com.burger.fresh;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * 
 * 				This is port where web service is deploy
 * 			
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BurgerStoreServiceProviderService", targetNamespace = "http://www.burger.com/fresh", wsdlLocation = "file:/C:/Users/VC1/workspace/spring-app-mobile/src/main/webapp/wsdl/burger.wsdl")
public class BurgerStoreServiceProviderService
    extends Service
{

    private final static URL BURGERSTORESERVICEPROVIDERSERVICE_WSDL_LOCATION;
    private final static WebServiceException BURGERSTORESERVICEPROVIDERSERVICE_EXCEPTION;
    private final static QName BURGERSTORESERVICEPROVIDERSERVICE_QNAME = new QName("http://www.burger.com/fresh", "BurgerStoreServiceProviderService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/VC1/workspace/spring-app-mobile/src/main/webapp/wsdl/burger.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BURGERSTORESERVICEPROVIDERSERVICE_WSDL_LOCATION = url;
        BURGERSTORESERVICEPROVIDERSERVICE_EXCEPTION = e;
    }

    public BurgerStoreServiceProviderService() {
        super(__getWsdlLocation(), BURGERSTORESERVICEPROVIDERSERVICE_QNAME);
    }

    public BurgerStoreServiceProviderService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BURGERSTORESERVICEPROVIDERSERVICE_QNAME, features);
    }

    public BurgerStoreServiceProviderService(URL wsdlLocation) {
        super(wsdlLocation, BURGERSTORESERVICEPROVIDERSERVICE_QNAME);
    }

    public BurgerStoreServiceProviderService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BURGERSTORESERVICEPROVIDERSERVICE_QNAME, features);
    }

    public BurgerStoreServiceProviderService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BurgerStoreServiceProviderService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BurgerStoreServiceProvider
     */
    @WebEndpoint(name = "BurgerStoreServiceProviderPort")
    public BurgerStoreServiceProvider getBurgerStoreServiceProviderPort() {
        return super.getPort(new QName("http://www.burger.com/fresh", "BurgerStoreServiceProviderPort"), BurgerStoreServiceProvider.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BurgerStoreServiceProvider
     */
    @WebEndpoint(name = "BurgerStoreServiceProviderPort")
    public BurgerStoreServiceProvider getBurgerStoreServiceProviderPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.burger.com/fresh", "BurgerStoreServiceProviderPort"), BurgerStoreServiceProvider.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BURGERSTORESERVICEPROVIDERSERVICE_EXCEPTION!= null) {
            throw BURGERSTORESERVICEPROVIDERSERVICE_EXCEPTION;
        }
        return BURGERSTORESERVICEPROVIDERSERVICE_WSDL_LOCATION;
    }

}
